FROM ruby:3.2.2-alpine3.17

# Expected args for user creation
ARG UID
ARG USER

# Install SO Dependencies and aplication user
RUN apk update && apk add postgresql-client postgresql-dev busybox-extras git build-base && \
    adduser -D -u "$UID" -h /app "$USER"

# rdkafka dependency
RUN apk add bash

# Install glibc to M1 macs
RUN apk add gcompat

# Change context to application user
USER $USER

# Define rails default dir
WORKDIR /app

# Prepare ruby deps to install
COPY --chown=$USER Gemfile* /app/

# Install production app dependencies
RUN bundle config force_ruby_platform true
RUN bundle install

# Expose Application port
EXPOSE 3000

# Calls the entrypoint
ENTRYPOINT [ "rails", "server", "-b", "0.0.0.0", "-p", "3000", "--pid", "/tmp/rails_server.pid" ]